#%RAML 1.0
---
title: APIRedirectTest API
baseUri: http://localhost/{version}
version: v1

/accounts:
  get:
    description: |
      Retrieve resource(s)
    responses:
      200:
        description: |
          Successfully retrieved resource(s)
/contacts:
 get:
   description: |
     Retrieve resource(s)
   responses:
     200:
       description: |
         Successfully retrieved resource(s)